[package]
name = "http_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "tester"
path = "src/tester.rs"

[dependencies]
dotenv = "0.15.0"
